//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaolisUI.ZaolisServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZaolisServiceClient.IZaolisService", CallbackContract=typeof(ZaolisUI.ZaolisServiceClient.IZaolisServiceCallback))]
    public interface IZaolisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Connect", ReplyAction="http://tempuri.org/IZaolisService/ConnectResponse")]
        BLL.Models.UserDTO Connect(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Connect", ReplyAction="http://tempuri.org/IZaolisService/ConnectResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO> ConnectAsync(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Disconnect", ReplyAction="http://tempuri.org/IZaolisService/DisconnectResponse")]
        void Disconnect(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Disconnect", ReplyAction="http://tempuri.org/IZaolisService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddUser", ReplyAction="http://tempuri.org/IZaolisService/AddUserResponse")]
        void AddUser(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddUser", ReplyAction="http://tempuri.org/IZaolisService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddAvatar", ReplyAction="http://tempuri.org/IZaolisService/AddAvatarResponse")]
        void AddAvatar(BLL.Models.AvatarDTO newAvatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddAvatar", ReplyAction="http://tempuri.org/IZaolisService/AddAvatarResponse")]
        System.Threading.Tasks.Task AddAvatarAsync(BLL.Models.AvatarDTO newAvatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/RegisterUser", ReplyAction="http://tempuri.org/IZaolisService/RegisterUserResponse")]
        void RegisterUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/RegisterUser", ReplyAction="http://tempuri.org/IZaolisService/RegisterUserResponse")]
        System.Threading.Tasks.Task RegisterUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByLoginPassword", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByLoginPasswordResponse")]
        bool IsExistsUserByLoginPassword(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByLoginPassword", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByLoginPasswordResponse")]
        System.Threading.Tasks.Task<bool> IsExistsUserByLoginPasswordAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByEmailResponse")]
        bool IsExistsUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByEmailResponse")]
        System.Threading.Tasks.Task<bool> IsExistsUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByLogin", ReplyAction="http://tempuri.org/IZaolisService/GetUserByLoginResponse")]
        BLL.Models.UserDTO GetUserByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByLogin", ReplyAction="http://tempuri.org/IZaolisService/GetUserByLoginResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetAllUsers", ReplyAction="http://tempuri.org/IZaolisService/GetAllUsersResponse")]
        BLL.Models.UserDTO[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetAllUsers", ReplyAction="http://tempuri.org/IZaolisService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/GetUserByEmailResponse")]
        BLL.Models.UserDTO GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetCodeFromEmailResponse")]
        int GetCodeFromEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetCodeFromEmailResponse")]
        System.Threading.Tasks.Task<int> GetCodeFromEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmailResponse")]
        int GetVerificationCodeFromEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmailResponse")]
        System.Threading.Tasks.Task<int> GetVerificationCodeFromEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/ForgetPassword", ReplyAction="http://tempuri.org/IZaolisService/ForgetPasswordResponse")]
        void ForgetPassword(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/ForgetPassword", ReplyAction="http://tempuri.org/IZaolisService/ForgetPasswordResponse")]
        System.Threading.Tasks.Task ForgetPasswordAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersPassword", ReplyAction="http://tempuri.org/IZaolisService/EditUsersPasswordResponse")]
        void EditUsersPassword(BLL.Models.UserDTO user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersPassword", ReplyAction="http://tempuri.org/IZaolisService/EditUsersPasswordResponse")]
        System.Threading.Tasks.Task EditUsersPasswordAsync(BLL.Models.UserDTO user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Request", ReplyAction="http://tempuri.org/IZaolisService/RequestResponse")]
        bool Request();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Request", ReplyAction="http://tempuri.org/IZaolisService/RequestResponse")]
        System.Threading.Tasks.Task<bool> RequestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/SendMessage", ReplyAction="http://tempuri.org/IZaolisService/SendMessageResponse")]
        void SendMessage(BLL.Models.MessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/SendMessage", ReplyAction="http://tempuri.org/IZaolisService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(BLL.Models.MessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetContacts", ReplyAction="http://tempuri.org/IZaolisService/GetContactsResponse")]
        BLL.Models.UserDTO[] GetContacts(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetContacts", ReplyAction="http://tempuri.org/IZaolisService/GetContactsResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetContactsAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddContact", ReplyAction="http://tempuri.org/IZaolisService/AddContactResponse")]
        void AddContact(BLL.Models.UserDTO add_to, BLL.Models.UserDTO newContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddContact", ReplyAction="http://tempuri.org/IZaolisService/AddContactResponse")]
        System.Threading.Tasks.Task AddContactAsync(BLL.Models.UserDTO add_to, BLL.Models.UserDTO newContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByName", ReplyAction="http://tempuri.org/IZaolisService/GetUserByNameResponse")]
        BLL.Models.UserDTO GetUserByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByName", ReplyAction="http://tempuri.org/IZaolisService/GetUserByNameResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersName", ReplyAction="http://tempuri.org/IZaolisService/EditUsersNameResponse")]
        void EditUsersName(BLL.Models.UserDTO user, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersName", ReplyAction="http://tempuri.org/IZaolisService/EditUsersNameResponse")]
        System.Threading.Tasks.Task EditUsersNameAsync(BLL.Models.UserDTO user, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersBio", ReplyAction="http://tempuri.org/IZaolisService/EditUsersBioResponse")]
        void EditUsersBio(BLL.Models.UserDTO user, string bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersBio", ReplyAction="http://tempuri.org/IZaolisService/EditUsersBioResponse")]
        System.Threading.Tasks.Task EditUsersBioAsync(BLL.Models.UserDTO user, string bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetChat", ReplyAction="http://tempuri.org/IZaolisService/GetChatResponse")]
        BLL.Models.ChatDTO GetChat(BLL.Models.UserDTO user, BLL.Models.UserDTO contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetChat", ReplyAction="http://tempuri.org/IZaolisService/GetChatResponse")]
        System.Threading.Tasks.Task<BLL.Models.ChatDTO> GetChatAsync(BLL.Models.UserDTO user, BLL.Models.UserDTO contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserChats", ReplyAction="http://tempuri.org/IZaolisService/GetUserChatsResponse")]
        BLL.Models.ChatDTO[] GetUserChats(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserChats", ReplyAction="http://tempuri.org/IZaolisService/GetUserChatsResponse")]
        System.Threading.Tasks.Task<BLL.Models.ChatDTO[]> GetUserChatsAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUsersByChat", ReplyAction="http://tempuri.org/IZaolisService/GetUsersByChatResponse")]
        BLL.Models.UserDTO[] GetUsersByChat(BLL.Models.ChatDTO chat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUsersByChat", ReplyAction="http://tempuri.org/IZaolisService/GetUsersByChatResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetUsersByChatAsync(BLL.Models.ChatDTO chat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetAvatar", ReplyAction="http://tempuri.org/IZaolisService/GetAvatarResponse")]
        BLL.Models.AvatarDTO GetAvatar(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetAvatar", ReplyAction="http://tempuri.org/IZaolisService/GetAvatarResponse")]
        System.Threading.Tasks.Task<BLL.Models.AvatarDTO> GetAvatarAsync(BLL.Models.UserDTO user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZaolisServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IZaolisService/RecieveMessage")]
        void RecieveMessage(BLL.Models.MessageDTO message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZaolisServiceChannel : ZaolisUI.ZaolisServiceClient.IZaolisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZaolisServiceClient : System.ServiceModel.DuplexClientBase<ZaolisUI.ZaolisServiceClient.IZaolisService>, ZaolisUI.ZaolisServiceClient.IZaolisService {
        
        public ZaolisServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ZaolisServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ZaolisServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ZaolisServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ZaolisServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public BLL.Models.UserDTO Connect(string login, string passwordHash) {
            return base.Channel.Connect(login, passwordHash);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO> ConnectAsync(string login, string passwordHash) {
            return base.Channel.ConnectAsync(login, passwordHash);
        }
        
        public void Disconnect(BLL.Models.UserDTO user) {
            base.Channel.Disconnect(user);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(BLL.Models.UserDTO user) {
            return base.Channel.DisconnectAsync(user);
        }
        
        public void AddUser(BLL.Models.UserDTO user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(BLL.Models.UserDTO user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public void AddAvatar(BLL.Models.AvatarDTO newAvatar) {
            base.Channel.AddAvatar(newAvatar);
        }
        
        public System.Threading.Tasks.Task AddAvatarAsync(BLL.Models.AvatarDTO newAvatar) {
            return base.Channel.AddAvatarAsync(newAvatar);
        }
        
        public void RegisterUser(string email) {
            base.Channel.RegisterUser(email);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(string email) {
            return base.Channel.RegisterUserAsync(email);
        }
        
        public bool IsExistsUserByLoginPassword(string login, string password) {
            return base.Channel.IsExistsUserByLoginPassword(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> IsExistsUserByLoginPasswordAsync(string login, string password) {
            return base.Channel.IsExistsUserByLoginPasswordAsync(login, password);
        }
        
        public bool IsExistsUserByEmail(string email) {
            return base.Channel.IsExistsUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsExistsUserByEmailAsync(string email) {
            return base.Channel.IsExistsUserByEmailAsync(email);
        }
        
        public BLL.Models.UserDTO GetUserByLogin(string login) {
            return base.Channel.GetUserByLogin(login);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByLoginAsync(string login) {
            return base.Channel.GetUserByLoginAsync(login);
        }
        
        public BLL.Models.UserDTO[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public BLL.Models.UserDTO GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public int GetCodeFromEmail(string email) {
            return base.Channel.GetCodeFromEmail(email);
        }
        
        public System.Threading.Tasks.Task<int> GetCodeFromEmailAsync(string email) {
            return base.Channel.GetCodeFromEmailAsync(email);
        }
        
        public int GetVerificationCodeFromEmail(string email) {
            return base.Channel.GetVerificationCodeFromEmail(email);
        }
        
        public System.Threading.Tasks.Task<int> GetVerificationCodeFromEmailAsync(string email) {
            return base.Channel.GetVerificationCodeFromEmailAsync(email);
        }
        
        public void ForgetPassword(BLL.Models.UserDTO user) {
            base.Channel.ForgetPassword(user);
        }
        
        public System.Threading.Tasks.Task ForgetPasswordAsync(BLL.Models.UserDTO user) {
            return base.Channel.ForgetPasswordAsync(user);
        }
        
        public void EditUsersPassword(BLL.Models.UserDTO user, string pass) {
            base.Channel.EditUsersPassword(user, pass);
        }
        
        public System.Threading.Tasks.Task EditUsersPasswordAsync(BLL.Models.UserDTO user, string pass) {
            return base.Channel.EditUsersPasswordAsync(user, pass);
        }
        
        public bool Request() {
            return base.Channel.Request();
        }
        
        public System.Threading.Tasks.Task<bool> RequestAsync() {
            return base.Channel.RequestAsync();
        }
        
        public void SendMessage(BLL.Models.MessageDTO message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(BLL.Models.MessageDTO message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public BLL.Models.UserDTO[] GetContacts(BLL.Models.UserDTO user) {
            return base.Channel.GetContacts(user);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetContactsAsync(BLL.Models.UserDTO user) {
            return base.Channel.GetContactsAsync(user);
        }
        
        public void AddContact(BLL.Models.UserDTO add_to, BLL.Models.UserDTO newContact) {
            base.Channel.AddContact(add_to, newContact);
        }
        
        public System.Threading.Tasks.Task AddContactAsync(BLL.Models.UserDTO add_to, BLL.Models.UserDTO newContact) {
            return base.Channel.AddContactAsync(add_to, newContact);
        }
        
        public BLL.Models.UserDTO GetUserByName(string name) {
            return base.Channel.GetUserByName(name);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByNameAsync(string name) {
            return base.Channel.GetUserByNameAsync(name);
        }
        
        public void EditUsersName(BLL.Models.UserDTO user, string name) {
            base.Channel.EditUsersName(user, name);
        }
        
        public System.Threading.Tasks.Task EditUsersNameAsync(BLL.Models.UserDTO user, string name) {
            return base.Channel.EditUsersNameAsync(user, name);
        }
        
        public void EditUsersBio(BLL.Models.UserDTO user, string bio) {
            base.Channel.EditUsersBio(user, bio);
        }
        
        public System.Threading.Tasks.Task EditUsersBioAsync(BLL.Models.UserDTO user, string bio) {
            return base.Channel.EditUsersBioAsync(user, bio);
        }
        
        public BLL.Models.ChatDTO GetChat(BLL.Models.UserDTO user, BLL.Models.UserDTO contact) {
            return base.Channel.GetChat(user, contact);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.ChatDTO> GetChatAsync(BLL.Models.UserDTO user, BLL.Models.UserDTO contact) {
            return base.Channel.GetChatAsync(user, contact);
        }
        
        public BLL.Models.ChatDTO[] GetUserChats(BLL.Models.UserDTO user) {
            return base.Channel.GetUserChats(user);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.ChatDTO[]> GetUserChatsAsync(BLL.Models.UserDTO user) {
            return base.Channel.GetUserChatsAsync(user);
        }
        
        public BLL.Models.UserDTO[] GetUsersByChat(BLL.Models.ChatDTO chat) {
            return base.Channel.GetUsersByChat(chat);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetUsersByChatAsync(BLL.Models.ChatDTO chat) {
            return base.Channel.GetUsersByChatAsync(chat);
        }
        
        public BLL.Models.AvatarDTO GetAvatar(BLL.Models.UserDTO user) {
            return base.Channel.GetAvatar(user);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.AvatarDTO> GetAvatarAsync(BLL.Models.UserDTO user) {
            return base.Channel.GetAvatarAsync(user);
        }
    }
}
