//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaolisUI.ZaolisServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZaolisServiceReference.IZaolisService")]
    public interface IZaolisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Connect", ReplyAction="http://tempuri.org/IZaolisService/ConnectResponse")]
        BLL.Models.UserDTO Connect(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Connect", ReplyAction="http://tempuri.org/IZaolisService/ConnectResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO> ConnectAsync(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Disconnect", ReplyAction="http://tempuri.org/IZaolisService/DisconnectResponse")]
        void Disconnect(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Disconnect", ReplyAction="http://tempuri.org/IZaolisService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddUser", ReplyAction="http://tempuri.org/IZaolisService/AddUserResponse")]
        void AddUser(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddUser", ReplyAction="http://tempuri.org/IZaolisService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddAvatar", ReplyAction="http://tempuri.org/IZaolisService/AddAvatarResponse")]
        void AddAvatar(BLL.Models.AvatarDTO newAvatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/AddAvatar", ReplyAction="http://tempuri.org/IZaolisService/AddAvatarResponse")]
        System.Threading.Tasks.Task AddAvatarAsync(BLL.Models.AvatarDTO newAvatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/RegisterUser", ReplyAction="http://tempuri.org/IZaolisService/RegisterUserResponse")]
        void RegisterUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/RegisterUser", ReplyAction="http://tempuri.org/IZaolisService/RegisterUserResponse")]
        System.Threading.Tasks.Task RegisterUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByLoginPassword", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByLoginPasswordResponse")]
        bool IsExistsUserByLoginPassword(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByLoginPassword", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByLoginPasswordResponse")]
        System.Threading.Tasks.Task<bool> IsExistsUserByLoginPasswordAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByEmailResponse")]
        bool IsExistsUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/IsExistsUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/IsExistsUserByEmailResponse")]
        System.Threading.Tasks.Task<bool> IsExistsUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByLogin", ReplyAction="http://tempuri.org/IZaolisService/GetUserByLoginResponse")]
        BLL.Models.UserDTO GetUserByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByLogin", ReplyAction="http://tempuri.org/IZaolisService/GetUserByLoginResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetAllUsers", ReplyAction="http://tempuri.org/IZaolisService/GetAllUsersResponse")]
        BLL.Models.UserDTO[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetAllUsers", ReplyAction="http://tempuri.org/IZaolisService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/GetUserByEmailResponse")]
        BLL.Models.UserDTO GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetUserByEmail", ReplyAction="http://tempuri.org/IZaolisService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetCodeFromEmailResponse")]
        int GetCodeFromEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetCodeFromEmailResponse")]
        System.Threading.Tasks.Task<int> GetCodeFromEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmailResponse")]
        int GetVerificationCodeFromEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmail", ReplyAction="http://tempuri.org/IZaolisService/GetVerificationCodeFromEmailResponse")]
        System.Threading.Tasks.Task<int> GetVerificationCodeFromEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/ForgetPassword", ReplyAction="http://tempuri.org/IZaolisService/ForgetPasswordResponse")]
        void ForgetPassword(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/ForgetPassword", ReplyAction="http://tempuri.org/IZaolisService/ForgetPasswordResponse")]
        System.Threading.Tasks.Task ForgetPasswordAsync(BLL.Models.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersPassword", ReplyAction="http://tempuri.org/IZaolisService/EditUsersPasswordResponse")]
        void EditUsersPassword(BLL.Models.UserDTO user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/EditUsersPassword", ReplyAction="http://tempuri.org/IZaolisService/EditUsersPasswordResponse")]
        System.Threading.Tasks.Task EditUsersPasswordAsync(BLL.Models.UserDTO user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Request", ReplyAction="http://tempuri.org/IZaolisService/RequestResponse")]
        bool Request();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZaolisService/Request", ReplyAction="http://tempuri.org/IZaolisService/RequestResponse")]
        System.Threading.Tasks.Task<bool> RequestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZaolisServiceChannel : ZaolisUI.ZaolisServiceReference.IZaolisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZaolisServiceClient : System.ServiceModel.ClientBase<ZaolisUI.ZaolisServiceReference.IZaolisService>, ZaolisUI.ZaolisServiceReference.IZaolisService {
        
        public ZaolisServiceClient() {
        }
        
        public ZaolisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZaolisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZaolisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZaolisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BLL.Models.UserDTO Connect(string login, string passwordHash) {
            return base.Channel.Connect(login, passwordHash);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO> ConnectAsync(string login, string passwordHash) {
            return base.Channel.ConnectAsync(login, passwordHash);
        }
        
        public void Disconnect(BLL.Models.UserDTO user) {
            base.Channel.Disconnect(user);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(BLL.Models.UserDTO user) {
            return base.Channel.DisconnectAsync(user);
        }
        
        public void AddUser(BLL.Models.UserDTO user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(BLL.Models.UserDTO user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public void AddAvatar(BLL.Models.AvatarDTO newAvatar) {
            base.Channel.AddAvatar(newAvatar);
        }
        
        public System.Threading.Tasks.Task AddAvatarAsync(BLL.Models.AvatarDTO newAvatar) {
            return base.Channel.AddAvatarAsync(newAvatar);
        }
        
        public void RegisterUser(string email) {
            base.Channel.RegisterUser(email);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(string email) {
            return base.Channel.RegisterUserAsync(email);
        }
        
        public bool IsExistsUserByLoginPassword(string login, string password) {
            return base.Channel.IsExistsUserByLoginPassword(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> IsExistsUserByLoginPasswordAsync(string login, string password) {
            return base.Channel.IsExistsUserByLoginPasswordAsync(login, password);
        }
        
        public bool IsExistsUserByEmail(string email) {
            return base.Channel.IsExistsUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsExistsUserByEmailAsync(string email) {
            return base.Channel.IsExistsUserByEmailAsync(email);
        }
        
        public BLL.Models.UserDTO GetUserByLogin(string login) {
            return base.Channel.GetUserByLogin(login);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByLoginAsync(string login) {
            return base.Channel.GetUserByLoginAsync(login);
        }
        
        public BLL.Models.UserDTO[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public BLL.Models.UserDTO GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<BLL.Models.UserDTO> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public int GetCodeFromEmail(string email) {
            return base.Channel.GetCodeFromEmail(email);
        }
        
        public System.Threading.Tasks.Task<int> GetCodeFromEmailAsync(string email) {
            return base.Channel.GetCodeFromEmailAsync(email);
        }
        
        public int GetVerificationCodeFromEmail(string email) {
            return base.Channel.GetVerificationCodeFromEmail(email);
        }
        
        public System.Threading.Tasks.Task<int> GetVerificationCodeFromEmailAsync(string email) {
            return base.Channel.GetVerificationCodeFromEmailAsync(email);
        }
        
        public void ForgetPassword(BLL.Models.UserDTO user) {
            base.Channel.ForgetPassword(user);
        }
        
        public System.Threading.Tasks.Task ForgetPasswordAsync(BLL.Models.UserDTO user) {
            return base.Channel.ForgetPasswordAsync(user);
        }
        
        public void EditUsersPassword(BLL.Models.UserDTO user, string pass) {
            base.Channel.EditUsersPassword(user, pass);
        }
        
        public System.Threading.Tasks.Task EditUsersPasswordAsync(BLL.Models.UserDTO user, string pass) {
            return base.Channel.EditUsersPasswordAsync(user, pass);
        }
        
        public bool Request() {
            return base.Channel.Request();
        }
        
        public System.Threading.Tasks.Task<bool> RequestAsync() {
            return base.Channel.RequestAsync();
        }
    }
}
